version: "3.8"
services:
  web:
    build: .
    container_name: flask_web
    environment:
      - docker=true
    restart: always
    ports:
      - "1337:1337"
    networks:
      - web-net

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - web-net

networks:
  web-net:
    driver: bridge
